"use client";

import { LocaleLink as Link } from "@/content/i18n";
import { CheckCircle, Warning } from "@phosphor-icons/react";
import { curriculum, faqs, methodBlocks, platform } from "@/content/platform";
import { useLang } from "@/content/i18n";
import { PublicFooter, PublicHeader } from "./site-chrome";
import { PathwayFinder } from "./pathway-finder";
import { PlatformStyle } from "./platform-style";
import { CoachEditorial } from "./coach-editorial";

export type PublicPageKind = "method" | "program" | "coach" | "faq" | "privacy" | "terms" | "refund-policy" | "health-disclaimer";

export function PublicPage({ kind }: { kind: PublicPageKind }) {
  const legal = ["privacy", "terms", "refund-policy", "health-disclaimer"].includes(kind);
  return <><PlatformStyle /><PublicHeader /><main id="main-content" className="min-h-[75dvh] pt-[4.5rem]">{kind === "method" && <MethodPage />}{kind === "program" && <ProgramPage />}{kind === "coach" && <CoachEditorial />}{kind === "faq" && <FaqPage />}{legal && <LegalPage kind={kind as "privacy" | "terms" | "refund-policy" | "health-disclaimer"} />}</main><PublicFooter /></>;
}

function PageHero({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <section className="border-b border-[var(--line)] bg-[var(--bg-raise)] py-[clamp(5rem,13vh,9rem)]"><div className="shell grid gap-8 lg:grid-cols-[.55fr_1.45fr]"><div><span className="eyebrow">{eyebrow}</span></div><div><h1 className="font-display text-[clamp(3.5rem,9vw,8rem)] leading-[.9]">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-[var(--ink-soft)]">{body}</p></div></div></section>; }

function MethodPage() { const { t } = useLang(); return <><PageHero eyebrow={t({ru:"Метод",en:"The method"})} title={t({ru:"СИЛА, КОТОРАЯ ДВИЖЕТСЯ.",en:"STRENGTH THAT MOVES."})} body={t({ru:"Борцовская подготовка соединяет силу, скорость и контроль. Ни один блок не работает отдельно.",en:"Wrestling preparation connects strength, speed, and control. No block works in isolation."})} /><section className="section"><div className="shell"><div className="border-t border-[var(--line-strong)]">{methodBlocks.map((block) => <article key={block.number} className="method-row"><span className="font-mono text-sm text-[var(--oxblood-bright)]">{block.number}</span><div><span className="eyebrow">{t(block.eyebrow)}</span><h2 className="mt-2 font-display text-4xl md:text-6xl">{t(block.title)}</h2></div><p className="leading-relaxed text-[var(--ink-soft)]">{t(block.body)}</p></article>)}</div><div className="mt-16"><PathwayFinder /></div><div className="mt-16 grid gap-8 border-y border-[var(--line)] py-12 lg:grid-cols-2"><div><span className="eyebrow">{t({ru:"Бодибилдинг",en:"Traditional bodybuilding"})}</span><h3 className="mt-3 font-display text-3xl">{t({ru:"Мышца в фокусе",en:"The muscle in focus"})}</h3><p className="mt-4 text-[var(--ink-soft)]">{t({ru:"Стабильные подходы и изолированная работа имеют ценность для роста и контроля.",en:"Stable sets and isolation work can be valuable for growth and control."})}</p></div><div><span className="eyebrow text-[var(--oxblood-bright)]">{t({ru:"Борцовский подход",en:"Wrestling-informed"})}</span><h3 className="mt-3 font-display text-3xl">{t({ru:"Тело как система",en:"The body as a system"})}</h3><p className="mt-4 text-[var(--ink-soft)]">{t({ru:"Сила производится, принимается и перенаправляется через хват, корпус и движение.",en:"Force is produced, resisted, and redirected through grip, trunk, and movement."})}</p></div></div></div></section></>; }

function ProgramPage() { const { t } = useLang(); return <><PageHero eyebrow={t({ru:"8-недельная программа",en:"Eight-week program"})} title={t({ru:"У РАБОТЫ ЕСТЬ ПОРЯДОК.",en:"THE WORK HAS AN ORDER."})} body={t({ru:"Три тренировки в неделю, варианты для зала и дома, прогрессия без лишней суеты.",en:"Three sessions each week, gym and home pathways, and progression without noise."})} /><section className="section"><div className="shell grid gap-14 lg:grid-cols-[.65fr_1.35fr]"><div><span className="eyebrow">{t({ru:"Учебный план",en:"Curriculum"})}</span><p className="mt-5 max-w-sm text-[var(--ink-soft)]">{t({ru:"От базы к мощности, затем к работе под усталостью.",en:"From baseline to power, then work under fatigue."})}</p></div><div>{curriculum.map(([num,title,meta,preview]) => <div key={num} className="grid grid-cols-[3rem_1fr_auto] gap-3 border-t border-[var(--line)] py-5"><span className="font-mono text-xs text-[var(--ink-mute)]">{num}</span><span className="font-display text-xl">{t(title)}</span><span className="font-mono text-[.62rem] uppercase text-[var(--ink-mute)]">{preview ? t({ru:"Превью",en:"Preview"}) : meta}</span></div>)}</div></div></section><section id="enter" className="section border-t border-[var(--line)] bg-[var(--bg-raise)]"><div className="shell max-w-3xl"><div className="pricing-panel"><span className="eyebrow">{t(platform.product.accessType)}</span><h2 className="mt-5 font-display text-5xl">{t(platform.product.name)}</h2><p className="mt-3 text-[var(--ink-soft)]">{t(platform.product.subtitle)}</p><Link href="/" className="action-button mt-8 w-full justify-center">{t({ru:"Войти по паролю",en:"Enter with password"})}</Link><p className="mt-4 text-center text-xs text-[var(--ink-mute)]">{t({ru:"Доступ к программе открывается по паролю.",en:"Program access is granted with the password."})}</p></div></div></section></>; }


function FaqPage() { const { t } = useLang(); return <><PageHero eyebrow="FAQ" title={t({ru:"ПЕРЕД ТЕМ, КАК НАЧАТЬ.",en:"BEFORE YOU BEGIN."})} body={t({ru:"Прямые ответы о подготовке, оборудовании, доступе и безопасности.",en:"Direct answers about training, equipment, access, and safety."})} /><section className="section"><div className="shell max-w-4xl">{faqs.map((item) => <article key={t(item.q)} className="border-t border-[var(--line)] py-7"><h2 className="font-display text-2xl">{t(item.q)}</h2><p className="mt-3 max-w-2xl leading-relaxed text-[var(--ink-soft)]">{t(item.a)}</p></article>)}</div></section></>; }

function LegalPage({ kind }: { kind: "privacy" | "terms" | "refund-policy" | "health-disclaimer" }) { const { t } = useLang(); const titles = { privacy:"Privacy policy", terms:"Terms and conditions", "refund-policy":"Refund policy", "health-disclaimer":"Health and fitness disclaimer" }; return <section className="section"><article className="shell max-w-3xl"><Warning size={28} className="text-[var(--oxblood-bright)]" /><span className="eyebrow mt-6 block">{t({ru:"Требуется юридическая проверка",en:"Legal review required"})}</span><h1 className="mt-4 font-display text-5xl md:text-7xl">{titles[kind]}</h1><p className="mt-8 text-lg leading-relaxed text-[var(--ink-soft)]">{kind === "health-disclaimer" ? t({ru:"Платформа предоставляет общую информацию о фитнесе, а не медицинскую помощь. Тренируйтесь в пределах своих возможностей. При травмах, симптомах или медицинских вопросах обратитесь к квалифицированному специалисту.",en:"This platform provides general fitness education, not medical advice. Train within your abilities. If you have an injury, symptoms, or medical concerns, consult an appropriate qualified professional."}) : t({ru:"Это редактируемая оболочка. CRAFT должен подтвердить юрисдикцию, реквизиты компании, сроки, возвраты и контактные данные до публикации.",en:"This is an editable shell. CRAFT must confirm jurisdiction, company details, terms, refund conditions, and contact information before publication."})}</p><div className="mt-10 flex items-center gap-3 border-t border-[var(--line)] pt-6 text-sm text-[var(--ink-mute)]"><CheckCircle size={18} />{t({ru:"Без выдуманных гарантий или юридических условий.",en:"No invented guarantees or legal terms."})}</div></article></section>; }
